name: Deployment
on: [push, workflow_dispatch]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install Node Js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install client deps
        run: npm install
      - name: Run linter
        run: npm run lint